apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-pak-deployer-job
  namespace: cloud-pak-deployer
spec:
  # ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: deployer
          image: quay.io/cloud-pak-deployer/cloud-pak-deployer:latest
          env:
            - name: CONFIG_DIR
              value: /data/config
            - name: STATUS_DIR
              value: /data/status
            - name: CP_ENTITLEMENT_KEY
              valueFrom:
                secretKeyRef:
                  name: cpd-entitlement
                  key: entitlement.key
            - name: SUBCOMMAND
              value: environment
            - name: ACTION
              value: apply
            - name: CPD_ACCEPT_LICENSES
              value: "true"
            - name: CPD_OC_LOGIN
              valueFrom:
                secretKeyRef:
                  name: oc-login-secret
                  key: oc-login-cmd
          volumeMounts:
            - name: config
              mountPath: /data/config
            - name: status
              mountPath: /data/status
      volumes:
        - name: config
          configMap:
            name: cpd-configmap
        - name: status
          persistentVolumeClaim:
            claimName: cpd-status-pvc
