---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: ibm-db2aaservice-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  operators:
    - name: ibm-db2aaservice-cp4d-operator
      namespace: cpd-operators
      scope: public
      packageName: ibm-db2aaservice-cp4d-operator
      sourceNamespace: cpd-operators
      installPlanApproval: Automatic
      channel: v7.2
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: ibm-db2aaservice-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  services:
    - name: ibm-db2aaservice-cp4d-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: opencontent-rabbitmq-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  operators:
    - name: rabbitmq-operator
      namespace: cpd-operators
      scope: public
      packageName: ibm-rabbitmq-operator
      sourceNamespace: cpd-operators
      installPlanApproval: Automatic
      channel: v1.0
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: opencontent-rabbitmq-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  services:
    - name: rabbitmq-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: opencontent-elasticsearch-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  operators:
    - name: elasticsearch-operator
      namespace: cpd-operators
      scope: public
      packageName: ibm-elasticsearch-operator
      sourceNamespace: cpd-operators
      installPlanApproval: Automatic
      channel: v1.1
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: opencontent-elasticsearch-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  services:
    - name: elasticsearch-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: ibm-cpd-ccs-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  operators:
    - name: ibm-cpd-ccs-operator
      namespace: cpd-operators
      scope: public
      packageName: ibm-cpd-ccs
      sourceNamespace: cpd-operators
      installPlanApproval: Automatic
      channel: v10.2
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: ibm-cpd-ccs-registry
  namespace: cpd
  labels:
    app.kubernetes.io/instance: olm-utils
    app.kubernetes.io/managed-by: olm-utils
    app.kubernetes.io/name: olm-utils
    release: 5.1.2
spec:
  services:
    - name: ibm-cpd-ccs-operator
      spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2u-operator
  namespace: cpd-operators
spec:
  channel: v7.2
  installPlanApproval: Automatic
  name: db2u-operator
  source: ibm-db2uoperator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-ccs-operator
  namespace: cpd-operators
spec:
  channel: v10.2
  installPlanApproval: Automatic
  name: ibm-cpd-ccs
  source: ibm-cpd-ccs-operator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2aaservice-cp4d-operator
  namespace: cpd-operators
spec:
  channel: v7.2
  installPlanApproval: Automatic
  name: ibm-db2aaservice-cp4d-operator
  source: ibm-db2aaservice-cp4d-operator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rabbitmq-operator
  namespace: cpd-operators
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-rabbitmq-operator
  source: ibm-rabbitmq-operator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cpd-openpages-operator
  namespace: cpd-operators
spec:
  channel: v8.2
  installPlanApproval: Automatic
  name: ibm-cpd-openpages-operator
  source: ibm-cpd-openpages-operator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2oltp-cp4d-operator-catalog-subscription
  namespace: cpd-operators
spec:
  channel: v7.2
  installPlanApproval: Automatic
  name: ibm-db2oltp-cp4d-operator
  source: ibm-db2oltp-cp4d-operator-catalog
  sourceNamespace: cpd-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-ca-operator-catalog-subscription
  namespace: cpd-operators
spec:
  channel: v27.2
  installPlanApproval: Automatic
  name: ibm-ca-operator
  source: ibm-ca-operator-catalog
  sourceNamespace: cpd-operators
